FROM resin/armv7hf-systemd:latest

ENV INITSYSTEM=on

RUN apt-get update && apt-get -y install xserver-common xserver-xorg-core xserver-xorg-input-all && apt-get -y install wget xorg && rm -rf /var/lib/apt/*

RUN echo "http://ftp.us.debian.org/debian/pool/main/libg/libgcrypt11/libgcrypt11_1.5.0-5+deb7u4_armhf.deb http://launchpadlibrarian.net/218525709/chromium-browser_45.0.2454.85-0ubuntu0.14.04.1.1097_armhf.deb http://launchpadlibrarian.net/218525711/chromium-codecs-ffmpeg-extra_45.0.2454.85-0ubuntu0.14.04.1.1097_armhf.deb" | xargs wget
RUN dpkg -i libgcrypt11_1.5.0-5+deb7u4_armhf.deb chromium-codecs-ffmpeg-extra_45.0.2454.85-0ubuntu0.14.04.1.1097_armhf.deb chromium-browser_45.0.2454.85-0ubuntu0.14.04.1.1097_armhf.deb && rm libgcrypt11_1.5.0-5+deb7u4_armhf.deb chromium-codecs-ffmpeg-extra_45.0.2454.85-0ubuntu0.14.04.1.1097_armhf.deb chromium-browser_45.0.2454.85-0ubuntu0.14.04.1.1097_armhf.deb

WORKDIR /usr/src/app
COPY . ./

CMD /usr/src/app/go.sh

