FROM resin/armv7hf-systemd:latest

ENV INITSYSTEM=on

RUN apt-get update \
	&& apt-get -y install xserver-common xserver-xorg-core xserver-xorg-input-all \
	&& apt-get -y install wget xorg lwm \
	&& apt-get -y install gconf-service libasound2 libatk1.0-0 libcairo2 libcups2 libdbus-1-3 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 \
	&& apt-get -y install libgnome-keyring0 libgtk2.0-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libpangoft2-1.0-0 libxss1 xdg-utils libexif12 \
	&& rm -rf /var/lib/apt/*

RUN echo "http://ftp.us.debian.org/debian/pool/main/libg/libgcrypt11/libgcrypt11_1.5.0-5+deb7u4_armhf.deb http://launchpadlibrarian.net/218525709/chromium-browser_45.0.2454.85-0ubuntu0.14.04.1.1097_armhf.deb http://launchpadlibrarian.net/218525711/chromium-codecs-ffmpeg-extra_45.0.2454.85-0ubuntu0.14.04.1.1097_armhf.deb" | xargs wget
RUN dpkg -i libgcrypt11_1.5.0-5+deb7u4_armhf.deb chromium-codecs-ffmpeg-extra_45.0.2454.85-0ubuntu0.14.04.1.1097_armhf.deb chromium-browser_45.0.2454.85-0ubuntu0.14.04.1.1097_armhf.deb \
	&& rm libgcrypt11_1.5.0-5+deb7u4_armhf.deb chromium-codecs-ffmpeg-extra_45.0.2454.85-0ubuntu0.14.04.1.1097_armhf.deb chromium-browser_45.0.2454.85-0ubuntu0.14.04.1.1097_armhf.deb

WORKDIR /usr/src/app
COPY . ./

CMD /usr/src/app/go.sh

